sudo: required
services: 
  - docker

before_install:
  - docker build -t tkircsi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tkircsi/docker-react npm run test

language: generic 